[project]
name = 'trait-test'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bar]
path = 'contracts/bar.clar'
clarity_version = 2
epoch = 2.5

[contracts.foo]
path = 'contracts/foo.clar'
clarity_version = 2
epoch = 2.5

[contracts.impl]
path = 'contracts/impl.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
